### ISSUE TITLE
Using "fix 1 all nvt temp 298.0 298.0 100.0"

### ISSUE THREAD

**Issue by ghost** [zhenxingwang/lammps-conp#19]
Hello, 

I wanted to ask if there is a difference between the two following commands:

fix 1 **all** nvt temp 298.0 298.0 100.0 (for ALL atoms in the electrolyte)
or
fix 1 **sol** nvt temp 298.0 298.0 100.0 (sol for atoms in the electrolyte)

Will the CONP code give different results even if the velocities and forces of the electrode (ele) atoms are 0, such as that below:

velocity ele set 0.0 0.0 0.0
fix 0 ele setforce 0.0 0.0 0.0

In the notes it says:"Electrodes need to be frozen (set the force on electrode atoms to 0 and exclude electrode atoms from integration)"

Does this imply that both the electrode forces and velocities need to be set to 0 AND be excluded in the "fix nvt"? 

Thank you

**Comment by srtee** [comment]
Hi,

I recommend using "fix nvt" only on the moving particles instead of group "all", for two reasons.

Firstly, this prevents any "accidents", for example if you forget to set "fix setforce" to keep the electrode particles frozen.

Secondly, "fix nvt" on group "all" will use a temperature compute on group "all" for thermostatting. Since this compute will include electrode atoms the temperature calculated will be too low, and the electrolyte will be thermostatted to a far too high temperature. Calling "fix nvt" on the electrolyte group will automatically thermostat to the temperature of only the electrolyte group, avoiding this error.

Please note, it doesn't look like the original maintainers are updating this package any more. The constant potential capacities in LAMMPS are now actively maintained either under my USER-CONP2 package, or the ELECTRODE package included in LAMMPS from stable version 23Jun2022 and onwards.

**Comment by ghost** [comment]
I see. thank you for the explanation and suggestion regarding the USER-CONP2 package.
